FROM ubuntu

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean

COPY process_video.sh /process_video.sh
RUN chmod +x /process_video.sh

ENTRYPOINT ["bash","process_video.sh"]
