# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vizzzz

service: lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  s3ToSqs:
    handler: handler.s3ToSqs
